name: Check IKOS on mac

on: [push, pull_request]

jobs:
  Install:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pick source tools
      run: |
        sudo xcode-select -s /Library/Developer/CommandLineTools
    - name: Update Homebrew
      run: |
        brew update --preinstall
    - name: Set env vars
      run: |
        echo "CPATH=$(xcrun --show-sdk-path)/usr/include" >> $GITHUB_ENV
        echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
    - name: Install Homebrew dependencies
      run: |
        echo "$CPATH"
        echo "$SDKROOT"
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./apron.rb
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./ikos.rb || cat /Users/runner/Library/Logs/Homebrew/ikos/04.make
