name: Check IKOS on mac

on: [push, pull_request]

jobs:
  Install:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: What xcode are you using
      run: |
        xcode-select -p
        echo "HOMEBREW_SDKROOT=$(xcrun --show-sdk-path --sdk macosx)" >> $GITHUB_ENV
    - name: Update Homebrew
      run: |
        brew update --preinstall
    - name: Install LLVM
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm@14
    - name: Show variables
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./apron.rb
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./ikos.rb || cat /Users/runner/Library/Logs/Homebrew/ikos/07.make
    - name: Test IKOS
      run: |
        ikos --version
