name: Check IKOS on mac

on: [push, pull_request]

jobs:
  Install:

    runs-on: macos-latest

    steps:
    - name: Update Homebrew
      run: |
        brew update --preinstall
    - name: Install Homebrew dependencies
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install nasa-sw-vnv/core/ikos
