name: Check IKOS on mac

on: [push, pull_request]

  # env:
  #   DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer


jobs:
  Install:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: |
        brew update --preinstall
    - name: Install Homebrew dependencies
      run: |
        g++ -c test.cpp
        # sudo xcode-select --install
        # sudo xcode-select -s /Applications/Xcode_15.4.app/
        # # echo "CPATH=$(xcrun --show-sdk-path)/usr/include" >> $GITHUB_ENV
        # # echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
        # # echo "$CPATH"
        # # echo "$SDKROOT"
        # env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./apron.rb
        # env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./ikos.rb || cat /Users/runner/Library/Logs/Homebrew/ikos/04.make
