name: Check IKOS on mac

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer


jobs:
  Install:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: What xcode are you using
      run: |
        xcode-select -p
    - name: Update Homebrew
      run: |
        brew update --preinstall
    - name: Install Homebrew dependencies
      run: |
        echo "Printing all stdints in the SDK PATH"
        find $(xcrun --show-sdk-path)/usr/include -iname 'stdint.h'
        echo "End of Printing all stdints in the SDK PATH"
        echo 'LDFLAGS="-L/opt/homebrew/opt/llvm@14/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm@14/lib/c++"' >> $GITHUB_ENV
        echo "LDFLAGS=-L/opt/homebrew/opt/llvm@14/lib" >> $GITHUB_ENV
        echo "CFLAGS=--verbose -I$(xcrun --show-sdk-path)/usr/include -I/opt/homebrew/opt/llvm@14/include" >> $GITHUB_ENV
        echo "CXXFLAGS=--verbose -I$(xcrun --show-sdk-path)/usr/include/c++/v1 -I$(xcrun --show-sdk-path)/usr/include -I/opt/homebrew/opt/llvm@14/include" >> $GITHUB_ENV
        echo "CMAKE_INCLUDE_PATH=$(xcrun --show-sdk-path)/usr/include:/opt/homebrew/opt/llvm@14/include" >> $GITHUB_ENV
        echo "CMAKE_LIBRARY_PATH=$(xcrun --show-sdk-path)/usr/lib:/opt/homebrew/opt/llvm@14/lib;/opt/homebrew/opt/llvm@14/lib/c++" >> $GITHUB_ENV
        echo "CPATH=$(xcrun --show-sdk-path)/usr/include" >> $GITHUB_ENV
        echo "SDKROOT=$(xcrun --show-sdk-path --sdk macosx)" >> $GITHUB_ENV
        echo "/opt/homebrew/opt/llvm@14/bin" >> $GITHUB_PATH
    - name: Install LLVM
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm@14
    - name: Show variables
      run: |
        echo "CPP Flags are"
        echo "${{ env.CPPFLAGS }}"
        echo "End of echo"
        pwd
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./apron.rb
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source ./ikos.rb || cat /Users/runner/Library/Logs/Homebrew/ikos/04.clang++ /Users/runner/Library/Logs/Homebrew/ikos/06.make
